name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: GCloud auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.BIGQUERY_KEY }}'
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install
        run: npm ci --loglevel error
      - name: Build and Test
        run: npm run lint && npm run test-silent
